### ISSUE TITLE
How to use your library with lrc file?

### ISSUE THREAD

**Issue by maxakash** [Moriafly/LyricViewX#2]
There is no documentation to add lyric view in layout.
Please help me with that.

**Comment by Moriafly** [comment]
Layout:
```xml
<com.dirror.lyricviewx.LyricViewX
    android:id="@+id/lyricViewX"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:lrcPadding="16dp">
</com.dirror.lyricviewx.LyricViewX>
```

In the Activity: 
```kt
val file = File("...") // lrc file path
lyricViewX.loadLyric(file)
```

**Comment by maxakash** [comment]
@Moriafly Is there any way to load lrc file directly from assets folder.
Or if I load from url, what should be the value of "charset" for the lrc file?

**Comment by Moriafly** [comment]
There are many ways to get the lyrics to a song, you can get the text of the lyrics in other ways and pass it to LyricViewX.
1. Get the LRC file of the song name. It can be read either directly into a File or as a stream, usually encoded in **UTF-8**.
2. Get inline lyrics of the song, such as ID3v2 lyrics tag of MP3 files, through some open source libraries (like mp3agic or jaudiotag)
3. Get online lyrics.The String retrieved can be accessed directly through lyricViewx.loadLyric (String).

**Comment by maxakash** [comment]
Ok got it, I used an input stream to convert the file to string. It works perfectly but throws an excpetion which I have mentioned in another issue.
