### ISSUE TITLE
Using setNormalColor is not changing the text color correctly.

### ISSUE THREAD

**Issue by maxakash** [Moriafly/LyricViewX#4]
I am trying to the change the normal color using setNormalColor but I am getting a different color in the result.

**Comment by Moriafly** [comment]
```kt    
    lyricViewX.setNormalColor(Color.rgb(255, 0, 0)) // Set the color to red, 
```
Did it not work? 😂

**Comment by maxakash** [comment]
Yes it worked. My bad, I was using R.color.requiredColor.
Also when the lyric is long, starting and end words are hidden. 

![WhatsApp Image 2021-05-30 at 8 02 23 PM](https://user-images.githubusercontent.com/17406944/120108286-283e1a80-c182-11eb-8327-2c07ea1846f9.jpeg)

**Comment by Moriafly** [comment]
The width of the lyric is equal to the width of the View - lrcPadding
You can set it in layout XML
![image](https://user-images.githubusercontent.com/62319450/120108956-f6d14900-c199-11eb-9eca-9bb9c80f17e1.png)

**Comment by maxakash** [comment]
Got it Thanks. Thats all I need.
