### ISSUE TITLE
updateTime功能传入Long类型无效

### ISSUE THREAD

**Issue by DIPENG-XU** [Moriafly/LyricViewX#6]
updateTime功能传入Long类型无效，进入到界面的时候还是在第一行，没有实现功能。
【小建议】：Kotlin作为包类开发的时候，可以考虑将类open方便开发的时候填补一些功能，我原本想自己弄一个继承于LyricViewX的类改写一下updateTime这个功能，但是这个类在Kotlin没有加入open自定义为final类无法实现继承。

**Comment by DIPENG-XU** [comment]
这个问题用延时可以解决，主要是因为View初始化，updateTime比View初始化执行动作更快导致View中没有数据进行updateTime，用handler延个时能够治标不治本处理，如果能够在源码中处理这个问题可能会更好

**Comment by Moriafly** [comment]
已在 1.3.0-beta01 更改
