### ISSUE TITLE
不知道为啥歌词里总是出现重复句，一句话重复2次或者重复4次，很奇怪

### ISSUE THREAD

**Issue by jamesrookie** [Moriafly/LyricViewX#9]
![image](https://user-images.githubusercontent.com/53305616/181898736-47a756f8-55b9-4963-b816-0d4df38617ae.png)

**Comment by Moriafly** [comment]
需要提供下原歌词文本

**Comment by jamesrookie** [comment]
![image](https://user-images.githubusercontent.com/53305616/181903424-365eef40-4d1e-463f-b504-9017a8061917.png)
左边是logcat打印的歌词，获取到的是没问题的，就是在app里出现了重复的情况

**Comment by jamesrookie** [comment]
对了，歌词是网易云那个nodejs版的api获取的

**Comment by Moriafly** [comment]
可以提供下完整歌词和相关代码吗？

**Comment by Moriafly** [comment]
是否使用了 loadLyricByUrl 过失的方法，或检查代码是否重复调用了加载函数。
